.PHONY: install start start-ios prebuild clean

install:
	npm install

start:
	npx expo start

start-ios:
	npx expo run:ios

prebuild:
	npx expo prebuild --clean

clean:
	rm -rf android ios node_modules package-lock.json .expo
